### ISSUE TITLE
Phonegap build doesn't support the 1.02 version

### ISSUE THREAD

**Issue by tsd333** [an-rahulpandey/cordova-plugin-dbcopy#10]
Hi,

Thanks for dedicating building cool stuff.  I placed SQlite file in www folder and used dbcopy plugin 1.02 version in my Cordova iOS app (I am using Visual Studio Tools for Apache Cordova CTP 3.1 which supports up to Cordova version 4.1.2.)  I used Phonegap Build cloud service to build the ipa file.  However, when I uploaded the required files to Phonegap Build, it showed that 1.02 version is not supported.  Currently, Phonegap Build only supports 1.0.0 version.  So I replaced the plugin to 1.0.0 and compiled the project via the Phonegap Build.  Now in my iPhone, when the app ran to the window.plugins.sqlDB.copy function, it popped up an error something like .... Cocoa error 260 .... and .... No such file or directory ... (except for the db name, I used exactly same code as you put in the document.)

I wonder if it is because that the 1.0.0 version needs the database to be placed in a Resource folder of the iOS app but I placed the db file in the www folder.  If so, could you please ask Phonegap to support your 1.02 version?  I used Phonegap Build cloud service because our organization doesn't want to buy a mac machine.

Thanks!

**Comment by an-rahulpandey** [comment]
Yes for 1.0 version you have to put the db in resources directory. 
As for Phonegap build, I have never submitted the plugin there, since they need a Paid account to do that.

**Comment by tsd333** [comment]
Thanks for confirming it.  I will check how Phonegap can see and review the new version of the plugin.  Hopefully they can support it soon.  Thanks again.
