### ISSUE TITLE
ios can't build

### ISSUE THREAD

**Issue by brenaud** [an-rahulpandey/cordova-plugin-dbcopy#12]
Tried with android, worked perfectly
Building with ios generates the following warning:

warning: no rule to process file '/Volumes/BEN/IonicCordovaProject1/IonicCordovaProject1/platforms/ios/IonicCordovaProject1/Plugins/me.rahul.plugins.sqlDB/sqlDB.h' of type sourcecode.c.h for architecture i386

Tried uninstalling/reinstalling, no luck so far

**Comment by an-rahulpandey** [comment]
Make sure sqlDB.h is not present in the compile source (Select Target Project -> Build Phase -> Compile Source).

**Comment by brenaud** [comment]
Thanks!
