### ISSUE TITLE
dbcopy doesn't work when icloud backup is disabled

### ISSUE THREAD

**Issue by smorstabilini** [an-rahulpandey/cordova-plugin-dbcopy#15]
using the SQLItePlugin in iOS is possible to disable iCloud backup specifying the "location:2" parameter to open a prepopulated database: 

db = sqlitePlugin.openDatabase({name: "my.db", location: 2, createFromLocation: 1});

With this configuration dbcopy doesn't see the original database and so calling sqlDB.copy() or sqlDB.remove() doesn't work as expected.
Any solution?

PS: thanks for the plugin!

**Comment by an-rahulpandey** [comment]
I am working on the iCloud backup disable functionality, will update the plugin in few days.

**Comment by smorstabilini** [comment]
thanks!

**Comment by an-rahulpandey** [comment]
You can use 1.0.3 version to pass the location parameter (check Readme file) similar to Sqlite Plugin.

**Comment by smorstabilini** [comment]
thanks, it works like a charm!
