### ISSUE TITLE
Copy database from myfolder

### ISSUE THREAD

**Issue by cuong1024** [an-rahulpandey/cordova-plugin-dbcopy#16]
Hi,
I want to copy my database.db from 'storage/sdcard0/myfolder/database.db' to default data locaion. How can I do it?
Thank a lot.

**Comment by an-rahulpandey** [comment]
Currently plugin doesn't allow you to copy the database from the custom folder location. It currently only allows users to copy the database from app www directory to default database location. However, its a nice feature to look at it, I will try to implement it for Android whenever I get a chance.

**Comment by cuong1024** [comment]
Thank a lot, an-rahulpandey
I hope that feature will coming soon. 
:+1:

**Comment by an-rahulpandey** [comment]
The current plugin version supports this now.
