### ISSUE TITLE
Fix LICENSE?

### ISSUE THREAD

**Issue by brodybits** [an-rahulpandey/cordova-plugin-dbcopy#18]
The LICENSE file specifies GPL, which will not work for many users, while plugin.xml specifies Apache 2.0 which is much better. Can you please make one consistent statement which license you want to publish under?

I am maintaining the Cordova-sqlite-storage plugin and this project could help many users. If you choose MIT and/or Apache 2.0, I will add a link to this project from the Cordova-sqlite-storage, Cordova-sqlcipher-adapter, and cordova-sqlite-evfree projects.

Thanks!

**Comment by an-rahulpandey** [comment]
Thanks for adding the link in the plugin repo. I have updated the license to Apache 2.0.

**Comment by brodybits** [comment]
Thanks for fixing. I added the link to the Cordova-sqlite-storage, Cordova-sqlcipher-adapter, and cordova-sqlite-evfree projects. Note that I do not expect this to work with sqlcipher on the Android version, since this project attempts to open the database will not work in case it is encrypted.

An alternative that could support all target platforms would be to simply use the File API to copy the database (you would have to determine the correct target directory per platform though).
