### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by sangariv** [an-rahulpandey/cordova-plugin-dbcopy#2]
Hi
Can you guide me to use this plugin in commandline ?
window.plugins is always undefined to me.

**Comment by blattmann** [comment]
I have also the problem that I am not able to talk to my sqlite db on an iphone.
In xcode I have this warning:

`warning: no rule to process file '/Library/WebServer/Documents/rcs/dev/platforms/ios/Myapp/Plugins/me.rahul.plugins.sqlDB/sqlDB.h' of type sourcecode.c.h for architecture arm64`

In the debug console I receive this:

- [debug] OPEN database: rcsappmobile.db
- [debug] Initializing SQLitePlugin
- [debug] Detected docs path: /var/mobile/Containers/Data/Application/<UUID>/Documents
- [debug] Detected Library path: /var/mobile/Containers/Data/Application/<UUID>/Library
- [debug] no cloud sync at path: /var/mobile/Containers/Data/Application/<UUID>/Library/LocalDatabase
- [debug] open full db path: /var/mobile/Containers/Data/Application/<UUID>/Library/LocalDatabase/rcsappmobile.db
- [debug] Good news: SQLite is thread safe!
- [debug] DB opened: rcsappmobile.db

I have no problems on Android!

I created also an issue on Stackoverflow with more info regarding my code: [http://stackoverflow.com/q/36705044/2425177](url)

Any ideas?

**Comment by an-rahulpandey** [comment]
See #25

**Comment by IoTFusion** [comment]
Can you help me? I added the sqlDB plugin using cordova, but still having call to unknown plugin: sqlDB error.

**Comment by an-rahulpandey** [comment]
@IoTFusion Try building your project with Cordova CLI.

**Comment by milanifour** [comment]
when db copy it crash app.

**Comment by an-rahulpandey** [comment]
Hi,

Make sure db file is present inside the www folder.

**Comment by milanifour** [comment]
my db present in www folder
basically my db copy but not whole.
my db size is 25 MB and when copy just start and reach to just 12 KB my app crashed.
it's says like "unfortunatley , your app closed".

**Comment by an-rahulpandey** [comment]
@milanifour Can you debug using Android Monitor located inside android sdk
tools directory - https://developer.android.com/studio/profile/monitor.html
