### ISSUE TITLE
Getting undefined in ionic framework

### ISSUE THREAD

**Issue by aanexplus** [an-rahulpandey/cordova-plugin-dbcopy#21]
I have wrapped my function withing $ionicPlatform function. I don't know if their is any other way to use this plugin in ionic framework. It return the error window.plugins is undefined. Any help will be appreciated.

**Comment by an-rahulpandey** [comment]
Try this
https://blog.nraboy.com/2015/01/deploy-ionic-framework-app-pre-filled-sqlite-db/
