### ISSUE TITLE
move functionality

### ISSUE THREAD

**Issue by evhar002** [an-rahulpandey/cordova-plugin-dbcopy#24]
Hello,

When pre-filled sqlite db size is too big, after it was copied. The application has two databases file. So this has problem with the application size. Could you can add a new move functionality (copy and remove source file).

For ex: Before sqlite installed app size : 25MB, pre-filled sqlite db size : 20MB. 
When the application installed the app size reached the 65MB. (app size + source sqlite + copeid sqlite).

Thanks in advance.

**Comment by JoergHolz** [comment]
+1

**Comment by an-rahulpandey** [comment]
Will start working on it in two weeks.

**Comment by arkadyzalko** [comment]
+1

**Comment by an-rahulpandey** [comment]
App directory is a read only directory, so we cannot move or delete any content from it. If you have any other suggestion, then please let me know.
