### ISSUE TITLE
Cant copy database

### ISSUE THREAD

**Issue by TopoSan** [an-rahulpandey/cordova-plugin-dbcopy#28]
Hi,
thanks for this great plugin. I use it on Android and there is no problem, but when i tried to use on Ipad (IOS 9.2), it says "TypeError: undefined is not an object (evaluating 'window.plugins.sqlDB') ".
I write  <script src="../plugins/cordova-plugin-dbcopy/www/sqlDB.js"></script> to init but i dont know why this doesn´t work. I use Inte XDK to test the aplicatión i´m doing.
¿Do you know what would be?
Thank you very much.

**Comment by an-rahulpandey** [comment]
Check if there is an entry for the plugin in cordova_plugins.js file which you can find at platforms/ios/www/ directory. Also try re-adding the plugin and then building it using Cordova CLI -

    cordova build ios

**Comment by TopoSan** [comment]
Thank you. I´ll try it.
