### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by smorstabilini** [an-rahulpandey/cordova-plugin-dbcopy#32]
Any plan to add windows 10 support?
By the way, many thanks for this plugin :)

**Comment by an-rahulpandey** [comment]
Hi,
I would also like to add Windows 10 in the platforms list, however, currently I do not have any Windows environment set up or device to work on.
Also I will welcome any pull request regarding that platform :-)

**Comment by smorstabilini** [comment]
Hi, 
I'll look for somebody on freelancer.com to have this done, even if  I have a very low budget.
Thanks

**Comment by an-rahulpandey** [comment]
@smorstabilini I am starting learning Windows plugin dev, will try to create this plugin.
