### ISSUE TITLE
Plugin not working for me at all

### ISSUE THREAD

**Issue by Sam747** [an-rahulpandey/cordova-plugin-dbcopy#36]
I am trying to implement following tutorial but with no success so far . No error log or anything is thrown back. Please suggest me where I might be wrong .

[https://www.thepolyglotdeveloper.com/2015/01/deploy-ionic-framework-app-pre-filled-sqlite-db/](url)

I am using following sample chinook.db
[(http://www.sqlitetutorial.net/sqlite-sample-database/)](url)

I am using Ionic framework to build for android. Also please tell me where exactly to put my prepopulated db or sqlite file. I am using this location as of now

platforms/android/assets

**Comment by an-rahulpandey** [comment]
You have to keep the db in www folder - https://github.com/an-rahulpandey/cordova-plugin-dbcopy#database-file-location
Also while using the dbcopy command you have to pass the location parameter. The guide which you pasted seems old.
See this - https://github.com/an-rahulpandey/cordova-plugin-dbcopy#copy

**Comment by Sam747** [comment]
Thankyou for the answer.

I was not defining the location parameter which was the root cause.
