### ISSUE TITLE
Copy Database from Device Storage issue 

### ISSUE THREAD

**Issue by milanifour** [an-rahulpandey/cordova-plugin-dbcopy#47]
We are trying to Copy Database from Device Storage but there is no any status return

**Comment by an-rahulpandey** [comment]
If you can provide some log, then it would be great. You can use [Android Monitor](https://developer.android.com/studio/profile/monitor.html) or ADB Logcat

**Comment by milanifour** [comment]
Now i can Copy database from Device Storage But getting one issue  
"attempt to write a readonly database (code 1032)"
After copy data when i am going to edit or insert at that time i Got this 
Please suggest me how we solve

**Comment by an-rahulpandey** [comment]
Can you delete the app and reinstall, also can you paste some code here?

**Comment by milanifour** [comment]
I tried with reinstall app but got same issue. (after restart app Database is working But not working with copy and then  use )

`    oncopyDbFromStorage: function () {
            var basePath = app.appConfig.filesDir + "/" + app.appConfig.filesSubDir + "/";


            window.plugins.sqlDB.checkDbOnStorage("amc_database", basePath, function (success2) {
                console.log(success2.message);
                window.plugins.sqlDB.copyDbFromStorage("amc_database", 0, basePath + "amc_database", true, function (success3) {
                    console.log(success3.message);
                    location.reload();
                    //var initialHref = window.location.href;
                    //    // Show splash screen (useful if your app takes time to load) 
                    //    navigator.splashscreen.show();
                    //    // Reload original app url (ie your index.html file)
                    //    window.location = initialHref;
                }, function (error3) {
                    console.log(error3.message);
                });
            }, function (error2) {
                console.log(error2.message);
            });
        },
    `

**Comment by milanifour** [comment]
Is there any option for progress bar.
I think progress bar feature you have to add
