### ISSUE TITLE
Check if database already exists

### ISSUE THREAD

**Issue by billy124** [an-rahulpandey/cordova-plugin-dbcopy#49]
Hi,

This is a great plugin, however I wanted to ask if there is a way to check if the database already exists before trying to copy it over?

Thank you

**Comment by an-rahulpandey** [comment]
This method doesn't copy  the database, if the database already exists - 
`window.plugins.sqlDB.copy(dbname, location, success,error);`
It goes to error callback with the db exists response and error code, see README.md for more details.
