### ISSUE TITLE
copyDbFromStorage: DB Not Present in www folder 

### ISSUE THREAD

**Issue by harikrishna266** [an-rahulpandey/cordova-plugin-dbcopy#50]
window.plugins.sqlDB.copyDbFromStorage('newyork.mbtiles', location, 'file:///storage/emulated/0//Uptour/map/newyork.mbtiles', isDeleteOldDb, function(success) {
        		resolve(success);
        	}, function(error) {
        		console.log(error, 'hgjk');
        		reject(error);
        	});

throws 400 DB Not Present in www folder

**Comment by an-rahulpandey** [comment]
I have modified the error callback, not it will show proper error message. Please install the plugin from Github.

**Comment by harikrishna266** [comment]
thank you
