### ISSUE TITLE
copyDbFromStorage seems to fail for Android 9

### ISSUE THREAD

**Issue by hohae** [an-rahulpandey/cordova-plugin-dbcopy#54]
I've done some tests with the brand new Android 9. According to the logs, everything is fine. But when sqlite opens the DB, it's empty. 
This seems to be the default behaviour of sqlite to create a new db if the db is not found during opening. This makes me think that the copyDbFromStorage does not copy the file.

Any ideas of how to debug that? It works fine from Android 4.3 to 8.1. It just fails on Android 9.

**Comment by an-rahulpandey** [comment]
can you post some code here, how you are doing that?

**Comment by hohae** [comment]
Hi,

i was able to fix it by adding the following line:

public class DatabaseHelper extends SQLiteOpenHelper {
…
       public void createdatabase(File dbPath, String source, final CallbackContext callbackContext) throws IOException {

             Log.d("CordovaLog","Inside CreateDatabase getAbsolutePath= "+dbPath.getAbsolutePath());
             Log.d("CordovaLog","Inside CreateDatabase path = "+dbPath.getPath());
             databasePath = dbPath.getAbsolutePath();

             this.getReadableDatabase();
             this.close();

             try {
                    copyDatabase(dbPath, source, callbackContext);
             } catch (IOException e) {
                    throw new Error(
                                 "Create Database Exception ============================ "
                                              + e);
             }

       }
…

Regards,
Holger

**Comment by an-rahulpandey** [comment]
Hmm...I have added the close and open functionality in the copy function, is your databasehelper.java file exactly like this or it is from old version - https://github.com/an-rahulpandey/cordova-plugin-dbcopy/blob/master/src/android/DatabaseHelper.java

**Comment by hohae** [comment]
Yes, it’s the latest version and I’ve just added the close() after the getReadableDatabase() call.

The problem seems to be that if you call getReadableDatabase() and then try to overwrite the database before closing, this does not work any more under Android 9. The DB opens correctly but it is the empty DB, not the copied one. Unfortunately, this does not throw an exception while copying the file.

See also this description: https://stackoverflow.com/questions/50476782/android-p-sqlite-no-such-table-error-after-copying-database-from-assets. It led me to the solution.
