### ISSUE TITLE
Build error in v 2.1.0

### ISSUE THREAD

**Issue by FLATT-Dev** [an-rahulpandey/cordova-plugin-dbcopy#56]
I got the following error building v 2.1.0 for a Cordova app 
**<project>\platforms\android\src\me\rahul\plugins\sqlDB\sqlDB.java:129: error: local variable dbName is accessed from within inner class; needs to be declared final 
myInput = cordova.getActivity().getAssets().open("www/" + dbName);**
v 2.0.0 works fine
I'm using jdk1.8.0_131
Anyone else encountered this? 
Thanks
Andy

**Comment by an-rahulpandey** [comment]
dbName is declared final on line number 93, can you check at that line and let me know

**Comment by FLATT-Dev** [comment]
No it's not.Looks like it did not make it into the release build.
Andy

**Comment by an-rahulpandey** [comment]
Please install 2.1.1

**Comment by FLATT-Dev** [comment]
Builds and works fine. Thank you!
Andy
