### ISSUE TITLE
copying on a usb storage

### ISSUE THREAD

**Issue by perpi-66** [an-rahulpandey/cordova-plugin-dbcopy#58]
here is the code :   this.platform.ready().then(() => {
      this.androidPermissions.requestPermissions(
        [
            this.androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE, 
            this.androidPermissions.PERMISSION.WRITE_EXTERNAL_STORAGE
        ]
    );
        this.sqlcopy.copyDbToStorage('ionic.db.sqlite', 0,'/storage/7ABC-88D4/' ,true)

which gives me in return this message
[11:27:20]  console.error: {"message":"/storage/7ABC-88D4/ionic.db.sqlite (Permission denied)","code":400}

**Comment by an-rahulpandey** [comment]
Hi,

Can you try copying it in storage download folder?
